(function() {var implementors = {};
implementors["chunkwm"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.bool.html\">bool</a>&gt; for <a class=\"struct\" href=\"chunkwm/prelude/struct.NumericBool.html\" title=\"struct chunkwm::prelude::NumericBool\">NumericBool</a>","impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;&amp;'a <a class=\"struct\" href=\"chunkwm/prelude/struct.NumericBool.html\" title=\"struct chunkwm::prelude::NumericBool\">NumericBool</a>&gt; for <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u8.html\">u8</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"type\" href=\"chunkwm/prelude/type.ApplicationRef.html\" title=\"type chunkwm::prelude::ApplicationRef\">ApplicationRef</a>&gt; for <a class=\"struct\" href=\"chunkwm/prelude/struct.Application.html\" title=\"struct chunkwm::prelude::Application\">Application</a>","impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;&amp;'a mut <a class=\"struct\" href=\"chunkwm/struct.RawApplication.html\" title=\"struct chunkwm::RawApplication\">RawApplication</a>&gt; for <a class=\"struct\" href=\"chunkwm/prelude/struct.Application.html\" title=\"struct chunkwm::prelude::Application\">Application</a>","impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;&amp;'a mut <a class=\"struct\" href=\"chunkwm/struct.RawWindow.html\" title=\"struct chunkwm::RawWindow\">RawWindow</a>&gt; for <a class=\"struct\" href=\"chunkwm/prelude/struct.Window.html\" title=\"struct chunkwm::prelude::Window\">Window</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"type\" href=\"chunkwm/prelude/type.WindowRef.html\" title=\"type chunkwm::prelude::WindowRef\">WindowRef</a>&gt; for <a class=\"struct\" href=\"chunkwm/prelude/struct.Window.html\" title=\"struct chunkwm::prelude::Window\">Window</a>",];
implementors["core_foundation"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.bool.html\">bool</a>&gt; for <a class=\"struct\" href=\"core_foundation/boolean/struct.CFBoolean.html\" title=\"struct core_foundation::boolean::CFBoolean\">CFBoolean</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"core_foundation/boolean/struct.CFBoolean.html\" title=\"struct core_foundation::boolean::CFBoolean\">CFBoolean</a>&gt; for <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.bool.html\">bool</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.i32.html\">i32</a>&gt; for <a class=\"struct\" href=\"core_foundation/number/struct.CFNumber.html\" title=\"struct core_foundation::number::CFNumber\">CFNumber</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.i64.html\">i64</a>&gt; for <a class=\"struct\" href=\"core_foundation/number/struct.CFNumber.html\" title=\"struct core_foundation::number::CFNumber\">CFNumber</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.f32.html\">f32</a>&gt; for <a class=\"struct\" href=\"core_foundation/number/struct.CFNumber.html\" title=\"struct core_foundation::number::CFNumber\">CFNumber</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.f64.html\">f64</a>&gt; for <a class=\"struct\" href=\"core_foundation/number/struct.CFNumber.html\" title=\"struct core_foundation::number::CFNumber\">CFNumber</a>","impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;&amp;'a <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.str.html\">str</a>&gt; for <a class=\"struct\" href=\"core_foundation/string/struct.CFString.html\" title=\"struct core_foundation::string::CFString\">CFString</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
